# Generated by Django 5.0.6 on 2024-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.JSONField(default=dict, verbose_name='Attributes'),
        ),
    ]
