# Generated by Django 5.0.6 on 2024-05-23 10:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_description_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(default='Description', verbose_name='Description'),
        ),
    ]
